name: Manually build on Github Actions

on:
  workflow_dispatch:
    inputs:
      path:
        description: 'Dockerfile path to be built'
        required: true
        default: 'pytorch-1.10.0/torchvision-0.11.0/cuda-11.1.1/ffmpeg-4.4/opencv-4.5.3/python-3.9/Dockerfile'

jobs:
  docker:
    runs-on: ubuntu-latest
#     if: "join(fromJSON(github.event.inputs.path), '') != ''" # preoceed only when we have something to build
    steps:
      -
        name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: true
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          docker-images: false
          swap-storage: true
      -
        name: Checkout
        uses: actions/checkout@v4
#       -
#         name: Set up QEMU
#         uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Get path and create tag
        id: dockerfile
        run: |
          filepath=${{ github.event.inputs.path }};
          echo "path=$filepath" >> $GITHUB_OUTPUT;
          tag=$(echo $filepath | sed -n 's#.*/\([^/]*\)/Dockerfile#\1#p');
          echo "tag=${tag}" >> $GITHUB_OUTPUT;
          date="$(TZ='UTC' date +'%Y%m%d')";
          tag_date="${tag}-${date}";
          echo "tag_date=${tag_date}" >> $GITHUB_OUTPUT;
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GIT_PACKAGES_TOKEN }}
      -
        name: Build and push Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ steps.dockerfile.outputs.path }}
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ steps.dockerfile.outputs.tag }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ steps.dockerfile.outputs.tag_date }}
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ steps.dockerfile.outputs.tag }}
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ steps.dockerfile.outputs.tag_date }}
